version: "2"
checks:
  argument-count:
    enabled: true
  complexity:
    enabled: true
  duplication:
    enabled: true
  eslint:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_patterns:
  - "tests/"
  - "vendor/"
